# Generated by Django 5.2.7 on 2025-11-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(help_text='Kod kraju, np. PL, US, GB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Krótki opis gatunku literackiego.')),
                ('typical_themes', models.CharField(blank=True, help_text='Typowe motywy i tematy występujące w tym gatunku.', max_length=200)),
                ('is_fiction', models.BooleanField(default=True, help_text='Czy gatunek jest fikcyjny (literatura piękna).')),
                ('popularity_rank', models.PositiveSmallIntegerField(default=0, help_text='Ocena popularności (0–10) według bibliotekarzy lub czytelników.')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_month', models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1)),
                ('book_format', models.CharField(choices=[('P', 'Papierowa'), ('E', 'E-book'), ('A', 'Audiobook')], default='P', max_length=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.author')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.genre')),
            ],
        ),
    ]
