# Generated by Django 5.2.7 on 2025-11-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_stanowisko_osoba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
