# Generated by Django 5.2.7 on 2025-12-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_osoba_data_dodania_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('change_osoba_owner', 'Pozwala przypisać inną osobę do obiektu Osoba.'), ('change_assign_to_stanowisko', 'Pozwala przypisać osobę do innego stanowiska.')]},
        ),
    ]
